# Generated by Django 3.2.6 on 2021-10-05 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tombora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='user_email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
