# Generated by Django 3.2.6 on 2021-10-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tombora', '0002_members_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_on', models.TimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('retype_password', models.CharField(max_length=100)),
                ('agreement', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Members',
        ),
    ]
