# Generated by Django 3.2.6 on 2021-10-10 07:12

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('tombora', '0003_auto_20211010_0822'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='member',
            managers=[
                ('memberAuth_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
